#!/usr/bin/env node
/**
 * Deterministic asset catalog codegen (see docs/architecture-decisions/0003).
 *
 * Reads the controlled SVG asset tree (`assets/`) and emits
 * `src/catalog/assets.generated.ts`, embedding every icon as an
 * `image/svg+xml;base64,` data URI. The catalog resolves semantic icon ids
 * against the generated map at compile time; no filesystem access happens at
 * render time and the compiled `dist/` is self-contained.
 *
 * Output is stable: same input tree, byte-identical output (no timestamps,
 * no ordering from directory enumeration). Run via `npm run generate:assets`;
 * the build invokes it automatically.
 */
import { mkdir, readdir, readFile, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

import prettier from 'prettier';

const ROOT = fileURLToPath(new URL('..', import.meta.url));
const ASSETS_DIR = join(ROOT, 'assets');
const OUT_FILE = join(ROOT, 'src', 'catalog', 'assets.generated.ts');

/** The controlled asset categories (VISION §8). Discovery is fixed to these. */
const CATEGORIES = ['archetypes', 'metrics', 'status', 'products', 'common'];

const header = [
  '// @generated by scripts/generate-assets.mjs — do not edit by hand.',
  '// The SVG files under assets/ are the source of truth; run',
  '// `npm run generate:assets` to regenerate this module.',
  '',
].join('\n');

async function collectEntries() {
  /** @type {Array<{ key: string; dataUri: string }>} */
  const entries = [];
  for (const category of CATEGORIES) {
    const dir = join(ASSETS_DIR, category);
    const files = (await readdir(dir)).filter((file) => file.endsWith('.svg')).sort();
    for (const file of files) {
      const name = file.slice(0, -'.svg'.length);
      const svg = await readFile(join(dir, file), 'utf8');
      // Every mock asset starts with an optional XML declaration followed by
      // the <svg> root element; anything else is a packaging mistake.
      const withoutDeclaration = svg.replace(/^<\?xml[^>]*\?>\s*/u, '');
      if (!withoutDeclaration.startsWith('<svg')) {
        throw new Error(`Asset is not an SVG document: assets/${category}/${file}`);
      }
      const base64 = Buffer.from(svg, 'utf8').toString('base64');
      entries.push({ key: `${category}/${name}`, dataUri: `data:image/svg+xml;base64,${base64}` });
    }
  }
  return entries;
}

const entries = await collectEntries();

if (entries.length === 0) {
  throw new Error(`No SVG assets found under ${ASSETS_DIR}`);
}

const body = entries.map(({ key, dataUri }) => `  '${key}':\n    '${dataUri}',`).join('\n');

const source = [
  header,
  '/**',
  ' * Every committed asset under assets/ as a render-ready data URI, keyed by',
  ' * `<category>/<name>` (e.g. "status/healthy").',
  ' *',
  ' * Values are passed directly to `pptxgenjs` `addImage({ data })`.',
  ' */',
  'export const ASSET_DATA_URIS: Readonly<Record<string, string>> = {',
  body,
  '};',
  '',
].join('\n');

// Format with the project's .prettierrc.json so the committed output matches
// `prettier --check` exactly; the format() API does not load config on its own.
const prettierOptions = await prettier.resolveConfig(OUT_FILE);
const formatted = await prettier.format(source, {
  ...prettierOptions,
  filepath: OUT_FILE,
  parser: 'typescript',
});
await mkdir(dirname(OUT_FILE), { recursive: true });
await writeFile(OUT_FILE, formatted);

console.log(`Generated ${OUT_FILE} from ${entries.length} SVG assets.`);
